os: linux
language: python
dist: focal

addons:
  apt:
    sources:
      - sourceline: "deb https://labs.picotech.com/debian/ picoscope main"
        key_url: "https://labs.picotech.com/debian/dists/picoscope/Release.gpg.key"
    packages:
      - libps4000
      - libps5000
      - libps6000
      - swig
      - gcc
      - libpcsclite-dev
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev
      - llvm-10
      - libllvm10
      - llvm-10-dev

jobs:
  include:
  - env:
    - USE_GMP=1
    - LLVM_CONFIG=/usr/bin/llvm-config-10
    python: "3.9"
  - env:
    - USE_GMP=0
    - LLVM_CONFIG=/usr/bin/llvm-config-10
    python: "3.9"
  - env:
    - USE_GMP=1
    - LLVM_CONFIG=/usr/bin/llvm-config-10
    python: "3.8"
  - env:
    - USE_GMP=0
    - LLVM_CONFIG=/usr/bin/llvm-config-10
    python: "3.8"

before_install:
  - git clone https://github.com/colinoflynn/pico-python
  - cd pico-python
  - python setup.py install
  - cd ..
  - git clone https://github.com/picotech/picosdk-python-wrappers
  - cd picosdk-python-wrappers
  - python setup.py install
  - cd ..

install:
  - pip install codecov
  - if [ $USE_GMP == 1 ]; then pip install -e ".[picoscope_sdk, picoscope_alt, chipwhisperer, smartcard, gmp, test, dev]"; fi
  - if [ $USE_GMP == 0 ]; then pip install -e ".[picoscope_sdk, picoscope_alt, chipwhisperer, smartcard, test, dev]"; fi

script:
  - make -i typecheck
  - make -i codestyle
  - make test

after_success:
  - codecov
